//Generated by Lightning Kite's Mirror plugin
//AUTOMATICALLY GENERATED AND WILL BE OVERRIDDEN IF THIS MESSAGE IS PRESENT
package com.lightningkite.mirror.archive.model

import com.lightningkite.kommon.collection.treeWalkDepthSequence
import com.lightningkite.mirror.info.MirrorClass
import com.lightningkite.mirror.info.*
import kotlin.reflect.KClass
import kotlinx.serialization.*
import mirror.kotlin.*

data class ConditionNotMirror<T: Any?>(
    val TMirror: MirrorType<T>
) : MirrorClass<Condition.Not<T>>() {
    
    override val mirrorClassCompanion: MirrorClassCompanion? get() = Companion
    companion object : MirrorClassCompanion {
        val TMirrorMinimal get() = AnyMirror.nullable
        
        override val minimal = ConditionNotMirror(TypeArgumentMirrorType("T", Variance.INVARIANT, TMirrorMinimal))
        override fun make(typeArguments: List<MirrorType<*>>): MirrorClass<*> = ConditionNotMirror(typeArguments[0] as MirrorType<Any?>)
    }
    
    override val typeParameters: Array<MirrorType<*>> get() = arrayOf(TMirror)
    @Suppress("UNCHECKED_CAST")
    override val kClass: KClass<Condition.Not<T>> get() = Condition.Not::class as KClass<Condition.Not<T>>
    override val modifiers: Array<Modifier> get() = arrayOf(Modifier.Data)
    override val packageName: String get() = "com.lightningkite.mirror.archive.model"
    override val localName: String get() = "Condition.Not"
    override val implements: Array<MirrorClass<*>> get() = arrayOf(ConditionMirror(TMirror))
    override val owningClass: KClass<*>? get() = Condition::class
    
    val fieldCondition: Field<Condition.Not<T>,Condition<T>> = Field(
        owner = this,
        index = 0,
        name = "condition",
        type = ConditionMirror(TMirror),
        optional = false,
        get = { it.condition },
        annotations = listOf<Annotation>()
    )
    
    override val fields: Array<Field<Condition.Not<T>, *>> = arrayOf(fieldCondition)
    
    override fun deserialize(decoder: Decoder): Condition.Not<T> {
        var conditionSet = false
        var fieldCondition: Condition<T>? = null
        val decoderStructure = decoder.beginStructure(this, TMirror)
        loop@ while (true) {
            when (decoderStructure.decodeElementIndex(this)) {
                CompositeDecoder.READ_ALL -> {
                    fieldCondition = decoderStructure.decodeSerializableElement(this, 0, ConditionMirror(TMirror))
                    conditionSet = true
                    break@loop
                }
                CompositeDecoder.READ_DONE -> break@loop
                0 -> {
                    fieldCondition = decoderStructure.decodeSerializableElement(this, 0, ConditionMirror(TMirror))
                    conditionSet = true
                }
                else -> {}
            }
        }
        decoderStructure.endStructure(this)
        if(!conditionSet) {
            throw MissingFieldException("condition")
        }
        return Condition.Not<T>(
            condition = fieldCondition as Condition<T>
        )
    }
    
    override fun serialize(encoder: Encoder, obj: Condition.Not<T>) {
        val encoderStructure = encoder.beginStructure(this, TMirror)
        encoderStructure.encodeSerializableElement(this, 0, ConditionMirror(TMirror), obj.condition)
        encoderStructure.endStructure(this)
    }
}
