//Generated by Lightning Kite's Mirror plugin
//AUTOMATICALLY GENERATED AND WILL BE OVERRIDDEN IF THIS MESSAGE IS PRESENT
package com.lightningkite.mirror.archive.model

import com.lightningkite.kommon.collection.treeWalkDepthSequence
import com.lightningkite.mirror.info.MirrorClass
import com.lightningkite.mirror.info.*
import kotlin.reflect.KClass
import kotlinx.serialization.*

class ConditionMirror<T: Any?>(
    val TMirror: MirrorType<T>
) : PolymorphicMirror<Condition<T>>() {
    
    companion object {
        val minimal = ConditionMirror(AnyMirror.nullable)
    }
    
    override val typeParameters: Array<MirrorType<*>> get() = arrayOf(TMirror)
    @Suppress("UNCHECKED_CAST")
    override val kClass: KClass<Condition<T>> get() = Condition::class as KClass<Condition<T>>
    override val modifiers: Array<Modifier> get() = arrayOf(Modifier.Sealed)
    override val implements: Array<MirrorClass<*>> get() = arrayOf()
    override val packageName: String get() = "com.lightningkite.mirror.archive.model"
    override val localName: String get() = "Condition"
}
