//Generated by Lightning Kite's Mirror plugin
//AUTOMATICALLY GENERATED AND WILL BE OVERRIDDEN IF THIS MESSAGE IS PRESENT
package com.lightningkite.mirror.archive.model

import com.lightningkite.kommon.collection.treeWalkDepthSequence
import com.lightningkite.mirror.info.MirrorClass
import com.lightningkite.mirror.info.*
import kotlin.reflect.KClass
import kotlinx.serialization.*
import mirror.kotlin.*
import com.lightningkite.mirror.info.MirrorClassFieldMirror

data class ConditionFieldMirror<T: Any, V: Any?>(
    val TMirror: MirrorType<T>,
    val VMirror: MirrorType<V>
) : MirrorClass<Condition.Field<T,V>>() {
    
    override val mirrorClassCompanion: MirrorClassCompanion? get() = Companion
    companion object : MirrorClassCompanion {
        override val minimal = ConditionFieldMirror(TypeArgumentMirrorType("T", AnyMirror), TypeArgumentMirrorType("V", AnyMirror.nullable))
        override fun make(typeArguments: List<MirrorType<*>>): MirrorClass<*> = ConditionFieldMirror(typeArguments[0] as MirrorType<Any>, typeArguments[1] as MirrorType<Any?>)
    }
    
    override val typeParameters: Array<MirrorType<*>> get() = arrayOf(TMirror, VMirror)
    @Suppress("UNCHECKED_CAST")
    override val kClass: KClass<Condition.Field<T,V>> get() = Condition.Field::class as KClass<Condition.Field<T,V>>
    override val modifiers: Array<Modifier> get() = arrayOf(Modifier.Data)
    override val packageName: String get() = "com.lightningkite.mirror.archive.model"
    override val localName: String get() = "Condition.Field"
    override val implements: Array<MirrorClass<*>> get() = arrayOf(ConditionMirror(TMirror))
    override val owningClass: KClass<*>? get() = Condition::class
    
    val fieldField: Field<Condition.Field<T,V>,MirrorClass.Field<T,V>> = Field(
        owner = this,
        index = 0,
        name = "field",
        type = MirrorClassFieldMirror(TMirror, VMirror),
        optional = false,
        get = { it.field },
        annotations = listOf<Annotation>()
    )
    
    val fieldCondition: Field<Condition.Field<T,V>,Condition<V>> = Field(
        owner = this,
        index = 1,
        name = "condition",
        type = ConditionMirror(VMirror),
        optional = false,
        get = { it.condition },
        annotations = listOf<Annotation>()
    )
    
    override val fields: Array<Field<Condition.Field<T,V>, *>> = arrayOf(fieldField, fieldCondition)
    
    override fun deserialize(decoder: Decoder): Condition.Field<T,V> {
        var fieldSet = false
        var fieldField: MirrorClass.Field<T,V>? = null
        var conditionSet = false
        var fieldCondition: Condition<V>? = null
        val decoderStructure = decoder.beginStructure(this, TMirror, VMirror)
        loop@ while (true) {
            when (decoderStructure.decodeElementIndex(this)) {
                CompositeDecoder.READ_ALL -> {
                    fieldField = decoderStructure.decodeSerializableElement(this, 0, MirrorClassFieldMirror(TMirror, VMirror))
                    fieldSet = true
                    fieldCondition = decoderStructure.decodeSerializableElement(this, 1, ConditionMirror(VMirror))
                    conditionSet = true
                    break@loop
                }
                CompositeDecoder.READ_DONE -> break@loop
                0 -> {
                    fieldField = decoderStructure.decodeSerializableElement(this, 0, MirrorClassFieldMirror(TMirror, VMirror))
                    fieldSet = true
                }
                1 -> {
                    fieldCondition = decoderStructure.decodeSerializableElement(this, 1, ConditionMirror(VMirror))
                    conditionSet = true
                }
                else -> {}
            }
        }
        decoderStructure.endStructure(this)
        if(!fieldSet) {
            throw MissingFieldException("field")
        }
        if(!conditionSet) {
            throw MissingFieldException("condition")
        }
        return Condition.Field<T,V>(
            field = fieldField as MirrorClass.Field<T,V>,
            condition = fieldCondition as Condition<V>
        )
    }
    
    override fun serialize(encoder: Encoder, obj: Condition.Field<T,V>) {
        val encoderStructure = encoder.beginStructure(this, TMirror, VMirror)
        encoderStructure.encodeSerializableElement(this, 0, MirrorClassFieldMirror(TMirror, VMirror), obj.field)
        encoderStructure.encodeSerializableElement(this, 1, ConditionMirror(VMirror), obj.condition)
        encoderStructure.endStructure(this)
    }
}
