//Generated by Lightning Kite's Mirror plugin
//AUTOMATICALLY GENERATED AND WILL BE OVERRIDDEN IF THIS MESSAGE IS PRESENT
package com.lightningkite.mirror.archive.model

import com.lightningkite.kommon.collection.treeWalkDepthSequence
import com.lightningkite.mirror.info.MirrorClass
import com.lightningkite.mirror.info.*
import kotlin.reflect.KClass
import kotlinx.serialization.*

class ConditionEqualMirror<T : Any?>(
        val TMirror: MirrorType<T>
) : MirrorClass<Condition.Equal<T>>() {

    companion object {
        val minimal = ConditionEqualMirror(AnyMirror.nullable)
    }

    override val typeParameters: Array<MirrorType<*>> get() = arrayOf(TMirror)
    @Suppress("UNCHECKED_CAST")
    override val kClass: KClass<Condition.Equal<T>>
        get() = Condition.Equal::class as KClass<Condition.Equal<T>>
    override val modifiers: Array<Modifier> get() = arrayOf(Modifier.Data)
    override val packageName: String get() = "com.lightningkite.mirror.archive.model"
    override val localName: String get() = "Condition.Equal"
    override val implements: Array<MirrorClass<*>> get() = arrayOf(ConditionMirror(TMirror))
    override val owningClass: KClass<*>? get() = Condition::class

    val fieldValue: Field<Condition.Equal<T>, T> = Field(
            owner = this,
            index = 0,
            name = "value",
            type = TMirror,
            optional = false,
            get = { it.value },
            annotations = listOf<Annotation>()
    )

    override val fields: Array<Field<Condition.Equal<T>, *>> = arrayOf(fieldValue)

    override fun deserialize(decoder: Decoder): Condition.Equal<T> {
        var valueSet = false
        var fieldValue: T? = null
        val decoderStructure = decoder.beginStructure(this, TMirror)
        loop@ while (true) {
            when (decoderStructure.decodeElementIndex(this)) {
                CompositeDecoder.READ_ALL -> {
                    fieldValue = decoderStructure.decodeSerializableElement(this, 0, TMirror)
                    valueSet = true
                    break@loop
                }
                CompositeDecoder.READ_DONE -> break@loop
                0 -> {
                    fieldValue = decoderStructure.decodeSerializableElement(this, 0, TMirror)
                    valueSet = true
                }
                else -> {
                }
            }
        }
        decoderStructure.endStructure(this)
        if (!valueSet) {
            throw MissingFieldException("value")
        }
        return Condition.Equal<T>(
                value = fieldValue as T
        )
    }

    override fun serialize(encoder: Encoder, obj: Condition.Equal<T>) {
        val encoderStructure = encoder.beginStructure(this, TMirror)
        encoderStructure.encodeSerializableElement(this, 0, TMirror, obj.value)
        encoderStructure.endStructure(this)
    }
}
