//Generated by Lightning Kite's Mirror plugin
//AUTOMATICALLY GENERATED AND WILL BE OVERRIDDEN IF THIS MESSAGE IS PRESENT
package com.lightningkite.mirror.archive.model

import com.lightningkite.kommon.collection.treeWalkDepthSequence
import com.lightningkite.mirror.info.MirrorClass
import com.lightningkite.mirror.info.*
import kotlin.reflect.KClass
import kotlinx.serialization.*

object ConditionAlwaysMirror : MirrorObject<Condition.Always>(Condition.Always) {
    @Suppress("UNCHECKED_CAST")
    override val kClass: KClass<Condition.Always> get() = Condition.Always::class as KClass<Condition.Always>
    override val modifiers: Array<Modifier> get() = arrayOf(Modifier.Object)
    override val packageName: String get() = "com.lightningkite.mirror.archive.model"
    override val localName: String get() = "Condition.Always"
    override val implements: Array<MirrorClass<*>> get() = arrayOf(ConditionMirror(AnyMirror.nullable))
    override val owningClass: KClass<*>? get() = Condition::class
    
}
