//Generated by Lightning Kite's Mirror plugin
//AUTOMATICALLY GENERATED AND WILL BE OVERRIDDEN IF THIS MESSAGE IS PRESENT
package com.lightningkite.mirror.archive.model

import com.lightningkite.mirror.info.*
import kotlin.reflect.KClass
import kotlinx.serialization.*
import mirror.kotlin.*

data class HasIdMirror<ID: Any?>(
    val IDMirror: MirrorType<ID>
) : PolymorphicMirror<HasId<ID>>() {
    
    override val mirrorClassCompanion: MirrorClassCompanion? get() = Companion
    companion object : MirrorClassCompanion {
        val IDMirrorMinimal get() = AnyMirror.nullable
        
        override val minimal = HasIdMirror(TypeArgumentMirrorType("ID", Variance.INVARIANT, IDMirrorMinimal))
        @Suppress("UNCHECKED_CAST")
        override fun make(typeArguments: List<MirrorType<*>>): MirrorClass<*> = HasIdMirror(typeArguments[0] as MirrorType<Any?>)
        
        @Suppress("UNCHECKED_CAST")
        fun make(
            IDMirror: MirrorType<*>? = null
        ) = HasIdMirror<Any?>(
            IDMirror = (IDMirror ?: IDMirrorMinimal) as MirrorType<Any?>
        )
    }
    
    override val typeParameters: Array<MirrorType<*>> get() = arrayOf(IDMirror)
    @Suppress("UNCHECKED_CAST")
    override val kClass: KClass<HasId<ID>> get() = HasId::class as KClass<HasId<ID>>
    override val modifiers: Array<Modifier> get() = arrayOf(Modifier.Interface)
    override val implements: Array<MirrorClass<*>> get() = arrayOf()
    override val packageName: String get() = "com.lightningkite.mirror.archive.model"
    override val localName: String get() = "HasId"
}
