//Generated by Lightning Kite's Mirror plugin
//AUTOMATICALLY GENERATED AND WILL BE OVERRIDDEN IF THIS MESSAGE IS PRESENT
package com.lightningkite.mirror.archive.model

import com.lightningkite.mirror.info.*
import kotlin.reflect.KClass
import kotlinx.serialization.*
import mirror.kotlin.*

data class LinkMirror<A: HasUuid, B: HasUuid>(
    val AMirror: MirrorType<A>,
    val BMirror: MirrorType<B>
) : PolymorphicMirror<Link<A,B>>() {
    
    override val mirrorClassCompanion: MirrorClassCompanion? get() = Companion
    companion object : MirrorClassCompanion {
        val AMirrorMinimal get() = HasUuidMirror
        val BMirrorMinimal get() = HasUuidMirror
        
        override val minimal = LinkMirror(TypeArgumentMirrorType("A", Variance.INVARIANT, AMirrorMinimal), TypeArgumentMirrorType("B", Variance.INVARIANT, BMirrorMinimal))
        @Suppress("UNCHECKED_CAST")
        override fun make(typeArguments: List<MirrorType<*>>): MirrorClass<*> = LinkMirror(typeArguments[0] as MirrorType<HasUuid>, typeArguments[1] as MirrorType<HasUuid>)

        @Suppress("UNCHECKED_CAST")
        fun make(
                AMirror: MirrorType<*>? = null,
                BMirror: MirrorType<*>? = null
        ) = LinkMirror<HasUuid, HasUuid>(
                AMirror = (AMirror ?: AMirrorMinimal) as MirrorType<HasUuid>,
                BMirror = (BMirror ?: BMirrorMinimal) as MirrorType<HasUuid>
        )
    }
    
    override val typeParameters: Array<MirrorType<*>> get() = arrayOf(AMirror, BMirror)
    @Suppress("UNCHECKED_CAST")
    override val kClass: KClass<Link<A,B>> get() = Link::class as KClass<Link<A,B>>
    override val modifiers: Array<Modifier> get() = arrayOf(Modifier.Interface)
    override val implements: Array<MirrorClass<*>> get() = arrayOf()
    override val packageName: String get() = "com.lightningkite.mirror.archive.model"
    override val localName: String get() = "Link"
}
