//Generated by Lightning Kite's Mirror plugin
//AUTOMATICALLY GENERATED AND WILL BE OVERRIDDEN IF THIS MESSAGE IS PRESENT
package com.lightningkite.mirror.archive.model

import com.lightningkite.mirror.info.MirrorClass
import com.lightningkite.mirror.info.MirrorType
import com.lightningkite.mirror.info.*
import kotlin.reflect.KClass

class OperationAddNumericMirror<T : Any?>(
        val TMirror: MirrorType<T>
) : PolymorphicMirror<Operation.AddNumeric<T>>() {

    companion object {
        val minimal = OperationAddNumericMirror(AnyMirror.nullable)
    }

    override val typeParameters: Array<MirrorType<*>> get() = arrayOf(TMirror)
    @Suppress("UNCHECKED_CAST")
    override val kClass: KClass<Operation.AddNumeric<T>>
        get() = Operation.AddNumeric::class as KClass<Operation.AddNumeric<T>>
    override val modifiers: Array<Modifier> get() = arrayOf(Modifier.Interface)
    override val implements: Array<MirrorClass<*>> get() = arrayOf(OperationMirror(TMirror))
    override val packageName: String get() = "com.lightningkite.mirror.archive.model"
    override val localName: String get() = "Operation.AddNumeric"
    override val owningClass: KClass<*>? get() = Operation::class
}
