//Generated by Lightning Kite's Mirror plugin
//AUTOMATICALLY GENERATED AND WILL BE OVERRIDDEN IF THIS MESSAGE IS PRESENT
package com.lightningkite.mirror.archive.model

import com.lightningkite.mirror.info.MirrorAnnotation
import com.lightningkite.mirror.info.MirrorClass
import com.lightningkite.mirror.info.*
import kotlin.reflect.KClass
import kotlinx.serialization.*
import mirror.kotlin.*

class PrimaryKeyMirror(
) : MirrorAnnotation {
    override val annotationType: KClass<out Annotation> get() = PrimaryKey::class
    override fun asMap(): Map<String, Any?> = mapOf(
    )
}
