//Generated by Lightning Kite's Mirror plugin
//AUTOMATICALLY GENERATED AND WILL BE OVERRIDDEN IF THIS MESSAGE IS PRESENT
package com.lightningkite.mirror.archive.model

import com.lightningkite.kommon.collection.treeWalkDepthSequence
import com.lightningkite.mirror.info.FieldInfo
import com.lightningkite.mirror.info.*
import kotlin.reflect.KClass

@Suppress("RemoveExplicitTypeArguments", "UNCHECKED_CAST", "USELESS_CAST")
object ConditionOrClassInfo : ClassInfo<Condition.Or<*>> {

    override val kClass: KClass<Condition.Or<*>> = Condition.Or::class
    override val modifiers: List<ClassInfo.Modifier> = listOf(ClassInfo.Modifier.Data)
    override val companion: Any? get() = null

    override val implements: List<Type<*>> = listOf(Type<Condition<Any?>>(Condition::class, listOf(TypeProjection(Type<Any?>(Any::class, listOf(), false), TypeProjection.Variance.INVARIANT)), false))

    override val packageName: String = "com.lightningkite.mirror.archive.model"
    override val owner: KClass<*>? = Condition::class
    override val ownerName: String? = "Condition"

    override val name: String = "Or"
    override val annotations: List<AnnotationInfo> = listOf()
    override val enumValues: List<Condition.Or<*>>? = null

    val fieldConditions = FieldInfo<Condition.Or<*>, List<Condition<Any?>>>(this, "conditions", Type<List<Condition<Any?>>>(List::class, listOf(TypeProjection(Type<Condition<Any?>>(Condition::class, listOf(TypeProjection(Type<Any?>(Any::class, listOf(), false), TypeProjection.Variance.INVARIANT)), false), TypeProjection.Variance.INVARIANT)), false), false, { it.conditions as List<Condition<Any?>> }, listOf())

    override val fields: List<FieldInfo<Condition.Or<*>, *>> = listOf(fieldConditions)

    override fun construct(map: Map<String, Any?>): Condition.Or<Any?> {
        //Gather variables
        val conditions: List<Condition<Any?>> = map["conditions"] as List<Condition<Any?>>
        //Handle the optionals

        //Finally do the call
        return Condition.Or<Any?>(
                conditions = conditions
        )
    }

}
