//Generated by Lightning Kite's Mirror plugin
//AUTOMATICALLY GENERATED AND WILL BE OVERRIDDEN IF THIS MESSAGE IS PRESENT
package com.lightningkite.mirror.archive.model

import com.lightningkite.kommon.collection.treeWalkDepthSequence
import com.lightningkite.mirror.info.FieldInfo
import com.lightningkite.mirror.info.*
import kotlin.reflect.KClass

@Suppress("RemoveExplicitTypeArguments", "UNCHECKED_CAST", "USELESS_CAST")
object ConditionGreaterThanOrEqualClassInfo : ClassInfo<Condition.GreaterThanOrEqual<*>> {

    override val kClass: KClass<Condition.GreaterThanOrEqual<*>> = Condition.GreaterThanOrEqual::class
    override val modifiers: List<ClassInfo.Modifier> = listOf(ClassInfo.Modifier.Data)
    override val companion: Any? get() = null

    override val implements: List<Type<*>> = listOf(Type<Condition<Comparable<Comparable<*>>>>(Condition::class, listOf(TypeProjection(Type<Comparable<Comparable<*>>>(Comparable::class, listOf(), false), TypeProjection.Variance.INVARIANT)), false))

    override val packageName: String = "com.lightningkite.mirror.archive.model"
    override val owner: KClass<*>? = Condition::class
    override val ownerName: String? = "Condition"

    override val name: String = "GreaterThanOrEqual"
    override val annotations: List<AnnotationInfo> = listOf()
    override val enumValues: List<Condition.GreaterThanOrEqual<*>>? = null

    val fieldValue = FieldInfo<Condition.GreaterThanOrEqual<*>, Comparable<Comparable<*>>>(this, "value", Type<Comparable<Comparable<*>>>(Comparable::class, listOf(), false), false, { it.value as Comparable<Comparable<*>> }, listOf())

    override val fields: List<FieldInfo<Condition.GreaterThanOrEqual<*>, *>> = listOf(fieldValue)

    override fun construct(map: Map<String, Any?>): Condition.GreaterThanOrEqual<Comparable<Comparable<*>>> {
        //Gather variables
        val value: Comparable<Comparable<*>> = map["value"] as Comparable<Comparable<*>>
        //Handle the optionals

        //Finally do the call
        return Condition.GreaterThanOrEqual<Comparable<Comparable<*>>>(
                value = value
        )
    }

}
