//Generated by Lightning Kite's Mirror plugin
//AUTOMATICALLY GENERATED AND WILL BE OVERRIDDEN IF THIS MESSAGE IS PRESENT
package com.lightningkite.mirror.archive.model

import com.lightningkite.mirror.info.ClassInfo
import com.lightningkite.mirror.info.FieldInfo
import com.lightningkite.mirror.serialization.toAttributeHashMap
import com.lightningkite.mirror.info.*
import kotlin.reflect.KClass

@Suppress("RemoveExplicitTypeArguments", "UNCHECKED_CAST", "USELESS_CAST")
object OperationClassInfo : ClassInfo<Operation<*>> {

    override val kClass: KClass<Operation<*>> = Operation::class
    override val modifiers: List<ClassInfo.Modifier> = listOf(ClassInfo.Modifier.Interface)
    override val companion: Any? get() = Operation

    override val implements: List<Type<*>> = listOf()

    override val packageName: String = "com.lightningkite.mirror.archive.model"
    override val owner: KClass<*>? = null
    override val ownerName: String? = null

    override val name: String = "Operation"
    override val annotations: List<AnnotationInfo> = listOf()
    override val enumValues: List<Operation<*>>? = null


    override val fields: List<FieldInfo<Operation<*>, *>> = listOf()

    override fun construct(map: Map<String, Any?>): Operation<Any?> = throw NotImplementedError()

}
